### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by SBroughton** [SBroughton/Anagram-Finder#1]
This is the error that I get when I try to run the program:

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3210)
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:261)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
	at java.util.ArrayList.add(ArrayList.java:458)
	at testmymethod2.TestMyMethod2.SeparateWords(TestMyMethod2.java:153)
	at testmymethod2.TestMyMethod2.main(TestMyMethod2.java:47)
C:\Users\User\AppData\Local\NetBeans\Cache\8.1\executor-snippets\run.xml:53: Java returned: 1
BUILD FAILED (total time: 6 minutes 2 seconds)

It has something to so with these lines:

 words.add(Line.substring(Start, End));

List <String> words=SeparateWords(Text);

**Comment by SBroughton** [comment]
I tried a new approach to creating an array list of words from the input file and now I am no longer seeing this error.
